git:
  submodules: false
before_install:
- sudo apt-get update
- sudo apt-get install parallel
- wget -O setup.sh http://mirror.racket-lang.org/installers/6.0.1/racket-6.0.1-x86_64-linux-ubuntu-precise.sh
- export PATH=$PATH:~/bin/
- chmod 770 setup.sh
- echo y >  setup_commands
- echo 1 >> setup_commands
- echo   >> setup_commands
language: node_js
node_js:
- 6.2.1
install:
- sudo ./setup.sh < setup_commands
- make install
before_script: make -j3
script:
- make clean-servers
- make all-pyret-test
notifications:
  slack:
    secure: kHQvp3HZL5GRY58XrGdRhZKtUvGrxgsAKMawYYNO4PA9NXlr5EYwbYBCrud1DNJs6kdEPK48ItSnsWXKoDZTS+g96b56t8vjHl2d98EN4WwvORj3g9NNiZ0SESL2LUwFa5vCxlnTbxfCQcfNpStGrwYZZ9DnIGTDuLO2EqZxvP0=
