// P2: translate lang/src/js/base/pyret-grammar.bnf -> a Lezer .grammar string.
// Mechanical EBNF transform; tokens are replayed from Pyret's own tokenizer
// (see tokens.js), so terminals map 1:1 to BNF terminal names.
const fs = require("fs");
const path = require("path");

const BNF = path.join(__dirname, "../lang/src/js/base/pyret-grammar.bnf");

// Lezer identifiers can't contain '-'; sanitize consistently (also used in tokens.js).
function san(name) { return name.replace(/-/g, "_"); }

function readRules() {
  let text = fs.readFileSync(BNF, "utf8");
  // Preprocess the 3 empty-alternative / leading-bar constructs into optionals.
  text = text
    .replace("(comma-binops [COMMA] | )", "[comma-binops [COMMA]]")
    .replace("(comma-ann-field [COMMA] | )", "[comma-ann-field [COMMA]]")
    .replace("construct-modifier: | LAZY", "construct-modifier: [LAZY]");

  const lines = text.split("\n");
  const RULE_START = /^([a-z][A-Za-z0-9-]*)\s*:(.*)$/;
  const rules = []; // {name, rhs}
  let cur = null;
  for (let raw of lines) {
    // strip C-style header and blank
    if (/^\s*\/\*/.test(raw) || /^\s*\*/.test(raw)) continue;
    // strip inline + full-line comments
    const hash = raw.indexOf("#");
    if (hash >= 0) raw = raw.slice(0, hash);
    if (raw.trim() === "") continue;
    const m = raw.match(RULE_START);
    if (m && raw[0] !== " " && raw[0] !== "\t") {
      cur = { name: m[1], rhs: m[2] };
      rules.push(cur);
    } else if (cur) {
      cur.rhs += " " + raw.trim();
    }
  }
  return rules;
}

const terminals = new Set();

// Tokenize an RHS string into atoms, then re-emit in Lezer syntax.
function convertRhs(rhs) {
  const toks = rhs.match(/[A-Za-z][A-Za-z0-9-]*|[\[\]()*+|]/g) || [];
  const stack = []; // 'opt' for [ , 'grp' for (
  let out = [];
  for (const t of toks) {
    if (t === "[") { stack.push("opt"); out.push("("); }
    else if (t === "(") { stack.push("grp"); out.push("("); }
    else if (t === "]" || t === ")") {
      const kind = stack.pop();
      out.push(kind === "opt" ? ")?" : ")");
    }
    else if (t === "*" || t === "+" || t === "|") out.push(t);
    else if (/^[A-Z]/.test(t)) { terminals.add(san(t)); out.push(san(t)); }
    else out.push(san(t)); // nonterminal
  }
  // join with spaces, but keep ? * + tight to their preceding )
  let s = out.join(" ")
    .replace(/\(\s+/g, "(")
    .replace(/\s+\)/g, ")")
    .replace(/\s+([*+?])/g, "$1");
  return s;
}

function main() {
  const rules = readRules();
  // Merge same-named productions (BNF lists alternatives as repeated `name:` lines).
  const grouped = new Map(); // sanitized name -> [converted rhs, ...]
  for (const r of rules) {
    if (r.name === "bad-expr") continue; // dangling in BNF (never referenced)
    const n = san(r.name);
    if (!grouped.has(n)) grouped.set(n, []);
    grouped.get(n).push(convertRhs(r.rhs));
  }
  const byName = new Map();
  for (const [n, alts] of grouped) byName.set(n, alts.join(" | "));

  // program is @top
  const top = byName.get("program");
  byName.delete("program");

  let g = "// GENERATED by gen-grammar.js from pyret-grammar.bnf — do not edit by hand\n";
  g += "@top Program { " + top + " }\n\n";
  for (const [name, rhs] of byName) {
    g += name + " { " + rhs + " }\n";
  }
  g += "\n@skip { Space }\n\n";
  const terms = [...terminals].sort();
  terms.push("Space");
  g += "@external tokens pyretTokens from \"./tokens\" {\n  " +
       terms.join(",\n  ") + "\n}\n";

  fs.writeFileSync(path.join(__dirname, "pyret.grammar"), g);
  fs.writeFileSync(path.join(__dirname, "terminals.json"),
                   JSON.stringify([...terminals].sort(), null, 0));
  console.log("rules:", rules.length, " terminals:", terminals.size);
  console.log("wrote pyret.grammar, terminals.json");
}
main();
