/*
  Minimal synchronous AMD loader for the handful of runtime-independent JS
  modules the TS compiler reuses from the existing codebase:

    - pyret-base/js/js-numbers      (src/js/base/js-numbers.js)
    - pyret-base/js/pyret-tokenizer (src/js/base/pyret-tokenizer.js)
    - pyret-base/js/pyret-parser    (generated by lib/jglr/parser-generator.js)
    - jglr/jglr, jglr/rnglr, jglr/cyclicJSON (lib/jglr/*.js)

  These files all use named `define("name", [deps], factory)` calls, so a
  tiny synchronous resolver suffices; we do not need requirejs.
*/

import * as fs from 'fs';
import * as path from 'path';
import * as vm from 'vm';

// Resolves module names to file paths. The pyret-lang root is found
// relative to this compiled file's location (build/ts-compiler/interop ->
// lang root), overridable for testing or alternate layouts.
let pyretLangRoot = path.join(__dirname, '..', '..', '..');

export function setPyretLangRoot(root: string): void {
  pyretLangRoot = root;
  pathOverrides.clear();
  cache.clear();
}

const pathOverrides = new Map<string, string>();

// The pyret-parser is generated at build time; callers must tell us where
// it lives (e.g. build/ts-compiler/js/pyret-parser.js).
export function setModulePath(name: string, filePath: string): void {
  pathOverrides.set(name, filePath);
  cache.delete(name);
}

function defaultPathFor(name: string): string {
  switch (name) {
    case 'pyret-base/js/js-numbers':
      return path.join(pyretLangRoot, 'src', 'js', 'base', 'js-numbers.js');
    case 'pyret-base/js/type-util':
      return path.join(pyretLangRoot, 'src', 'js', 'base', 'type-util.js');
    case 'pyret-base/js/pyret-tokenizer':
      return path.join(pyretLangRoot, 'src', 'js', 'base', 'pyret-tokenizer.js');
    case 'pyret-base/js/pyret-parser':
      return path.join(pyretLangRoot, 'build', 'ts-compiler', 'js', 'pyret-parser.js');
    case 'jglr/jglr':
      return path.join(pyretLangRoot, 'lib', 'jglr', 'jglr.js');
    case 'jglr/rnglr':
      return path.join(pyretLangRoot, 'lib', 'jglr', 'rnglr.js');
    case 'jglr/cyclicJSON':
      return path.join(pyretLangRoot, 'lib', 'jglr', 'cyclicJSON.js');
    default:
      throw new Error(`amd loader: unknown module '${name}'`);
  }
}

const cache = new Map<string, any>();

export function amdRequire(name: string): any {
  if (cache.has(name)) return cache.get(name);
  const filePath = pathOverrides.get(name) ?? defaultPathFor(name);
  const src = fs.readFileSync(filePath, 'utf8');

  let result: any = undefined;
  let sawDefine = false;
  function define(...args: any[]): void {
    // Forms used by our modules:
    //   define("name", factory)
    //   define("name", [deps], factory)
    //   define([deps], factory)   (defensive)
    sawDefine = true;
    let deps: string[] = [];
    let factory: any;
    let i = 0;
    if (typeof args[i] === 'string') i++;
    if (Array.isArray(args[i])) { deps = args[i]; i++; }
    factory = args[i];
    const resolved = deps.map((d) => amdRequire(d));
    result = typeof factory === 'function' ? factory(...resolved) : factory;
  }
  (define as any).amd = {};

  // Run in the host realm (like requirejs under node does): the modules
  // pass values to each other (e.g. pyret-parser's serialized rule
  // actions are checked with `instanceof Array` inside rnglr.js), so
  // separate vm realms would break those checks.
  const wrapped = vm.runInThisContext(
    '(function(define, require, module, exports) {' + src + '\n})',
    { filename: filePath }
  );
  wrapped(define, undefined, undefined, undefined);
  if (!sawDefine) {
    throw new Error(`amd loader: ${filePath} did not call define()`);
  }
  cache.set(name, result);
  return result;
}
