name: lang/ tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lang

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: install
      run: make install

    - name: build
      run: make

    - name: run tests
      run: make all-pyret-test

